NAME="util-macros"
VERS="1.20.2"
DESC="m4 macros used by Xorg"
UPST="https://gitlab.freedesktop.org/xorg/util/macros.git"

SOURCE="https://www.x.org/pub/individual/util/util-macros-$VERS.tar.xz"
EXTRA=()

2b() {

. e-xorg

b-cfg $XORG_CONFIG
b-mi

}
