NAME="xkeyboard-config"
VERS="2.44"
DESC="X keyboard configuration database"
CATG=""
UPST="https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config.git"
DEPS=(
    "meson"
    "python"
    "xkbcomp"
)

SOURCE="https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms 
nj
ni

}
