NAME="xcb-util-wm"
VERS="0.4.2"
DESC="Client and window-manager helpers for EWMH and ICCCM"
CATG=""
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-wm.git"
DEPS=(
    "libxcb"
    "xcb-proto"
)

SOURCE="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
