# NOTE: The only package that relies on luit is xterm, which is not currently provided.
# TODO: Either add xterm or drop luit, referencing the above.
NAME="luit"
VERS="20240910"
DESC="Filter that can be run between an arbitrary application and a UTF-8 terminal emulator"
CATG=""
UPST=""
DEPS=(
    "libfontenc"
    "libx11"
)

SOURCE="https://invisible-mirror.net/archives/luit/luit-$VERS.tgz"
EXTRA=()

2b() {

cfg
mk
mi

}
