NAME="xcb-util-cursor"
VERS="0.1.5"
DESC="XCB cursor library"
CATG=""
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-cursor.git"
DEPS=(
    "libxcb"
    "xcb-proto"
)

SOURCE="https://xcb.freedesktop.org/dist/xcb-util-cursor-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}