NAME="xcb-util-keysyms"
VERS="0.4.1"
DESC="Standard X constants and conversion to/from keycodes"
CATG=""
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-keysyms.git"
DEPS=(
    "libxcb"
    "xcb-proto"
)

SOURCE="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
