NAME="xcb-util-renderutil"
VERS="0.3.10"
DESC="Convenience functions for the X Render extension"
CATG=""
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-render-util.git"
DEPS=(
    "libxcb"
    "xcb-proto"
)

SOURCE="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
