NAME="xcb-util-errors"
VERS="1.0.1"
DESC="XCB errors library"
CATG=""
UPST="https://gitlab.freedesktop.org/xorg/lib/libxcb-errors.git"
DEPS=(
    "libxcb"
    "xcb-proto"
)

SOURCE="https://xcb.freedesktop.org/dist/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}