NAME="xcb-util-xrm"
VERS="1.3"
DESC="XCB utility functions for the X Resource Manager"
CATG=""
UPST="https://github.com/Airblader/$NAME.git"
DEPS=(
    "util-macros"
    "xcb-util"
    "libx11"
)

SOURCE="https://github.com/Airblader/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

}
